name: Actualizar Feeds RSS

# Ejecutar cada 12 horas y también manualmente
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  actualizar-feeds:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repo
      - name: Chequear repo
        uses: actions/checkout@v3

      # 2️⃣ Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Instalar feedparser
      - name: Instalar feedparser
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      # 4️⃣ Ejecutar lector.py
      - name: Ejecutar lector.py
        run: python lector.py

      # 5️⃣ Subir feeds.json actualizado si hay cambios
      - name: Subir feeds.json actualizado
        run: |
          set -e
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f feeds.json
          if ! git diff --cached --quiet; then
            git commit -m "Actualización automática de feeds [ci skip]"
            git push origin main
          else
            echo "No hay cambios, no se hace commit"
          fi
