name: Actualizar Feeds RSS

on:
  schedule:
    - cron: "0 */12 * * *"  # Cada 12 horas
  workflow_dispatch:        # Permite ejecutar manualmente

jobs:
  actualizar-feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar feedparser
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Ejecutar lector.py
        run: python lector.py

      - name: Subir feeds.json actualizado
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f feeds.json
          git diff --cached --exit-code || git commit -m "Actualización automática de feeds [ci skip]"
          git diff --cached --exit-code || git push origin main
